### ISSUE TITLE
Scraping info pour les continents

### ISSUE THREAD

**Issue by amelie-lr** [amelie-lr/FAS1002_projet-finsession#1]
Bonjour @SamGuay,

J'essaie depuis tantôt d'aller chercher l'info pour ajouter la variable sur les continents, pas mal certaine que mon code est bon, mais ça ne me retourne rien et j'ai l'erreur suivante :

```
html <- "https://ourworldindata.org/grapher/continents-according-to-our-world-in-data?tab=table"

data_continents <- read_html(x = html) %>%
    html_element(css = ".data-table") %>% 
    html_table()
```
> Error in UseMethod("html_table") : 
> no applicable method for 'html_table' applied to an object of class "xml_missing"

Quand j'enlève la dernière commande, ça me retourne un élément vide avec *xml_missing* sous type.

J'ai beau googler et essayer autres choses, rien ne fonctionne.
Help!

Merci,

Amélie

**Comment by SamGuay** [comment]
Bonjour! 

Ton code est bon, mais le site semble généré dynamiquement, donc le scraping ne fonctionne pas. Par contre, je peux t'orienter vers  un package qui risque de te sauver une certaine gymnastique, soit [countrycode](https://vincentarelbundock.github.io/countrycode/)! Le package contient tout ce dont tu as besoin pour créer la variable des continents!

Laisse-moi savoir si tu as des questions.

**Comment by amelie-lr** [comment]
Ça fonctionne, merci!
